SET NOCOUNT ON;
GO

DECLARE @now DATETIME2 = SYSDATETIME();
DECLARE @pwd NVARCHAR(255) = N'$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'; -- password

DECLARE @roleAdmin BIGINT = (SELECT TOP 1 id FROM dbo.roles WHERE role_name = N'Admin');
DECLARE @roleIT BIGINT = (SELECT TOP 1 id FROM dbo.roles WHERE role_name = N'ITWorker');
DECLARE @roleDoctor BIGINT = (SELECT TOP 1 id FROM dbo.roles WHERE role_name = N'Doctor');
DECLARE @roleNurse BIGINT = (SELECT TOP 1 id FROM dbo.roles WHERE role_name = N'Nurse');
DECLARE @rolePatient BIGINT = (SELECT TOP 1 id FROM dbo.roles WHERE role_name = N'Patient');
DECLARE @roleApplicant BIGINT = (SELECT TOP 1 id FROM dbo.roles WHERE role_name = N'Applicant');
DECLARE @roleDonor BIGINT = (SELECT TOP 1 id FROM dbo.roles WHERE role_name = N'Donor');

DECLARE @deptBlood BIGINT = (SELECT TOP 1 id FROM dbo.departments WHERE dept_name = N'Blood Bank');
DECLARE @deptCardio BIGINT = (SELECT TOP 1 id FROM dbo.departments WHERE dept_name = N'Cardiology & Vascular Medicine');
DECLARE @deptGeneral BIGINT = (SELECT TOP 1 id FROM dbo.departments WHERE dept_name = N'General Medicine');
DECLARE @deptNeuro BIGINT = (SELECT TOP 1 id FROM dbo.departments WHERE dept_name = N'Neurology & Neurosurgery');

IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'admin.seed@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Admin Seed', N'Admin Seed', N'admin.seed@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'it.blood@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Blood IT', N'Blood Bank IT Worker', N'it.blood@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'it.general@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'General IT', N'General IT Worker', N'it.general@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'doctor.rahim@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Dr Rahim', N'Dr Rahim Karim', N'doctor.rahim@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'doctor.sara@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Dr Sara', N'Dr Sara Ahmed', N'doctor.sara@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'nurse.blood@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Nurse Blood', N'Nurse Blood Specialist', N'nurse.blood@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'nurse.ward@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Nurse Ward', N'Nurse Ward Care', N'nurse.ward@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'patient.anik@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Patient Anik', N'Anik Hasan', N'patient.anik@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'patient.mina@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Patient Mina', N'Mina Akter', N'patient.mina@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'patient.rafi@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Patient Rafi', N'Rafi Chowdhury', N'patient.rafi@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'donor.arif@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Donor Arif', N'Arif Hossain', N'donor.arif@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'donor.nila@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Donor Nila', N'Nila Sultana', N'donor.nila@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'donor.kamal@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Donor Kamal', N'Kamal Uddin', N'donor.kamal@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'applicant.pending.doctor@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Applicant Doctor', N'Pending Doctor Applicant', N'applicant.pending.doctor@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'applicant.pending.nurse@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Applicant Nurse', N'Pending Nurse Applicant', N'applicant.pending.nurse@lifelink.test', @pwd, N'Active', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.users WHERE email = N'applicant.rejected.it@lifelink.test') INSERT INTO dbo.users (name, full_name, email, password, account_status, created_at, updated_at) VALUES (N'Applicant IT Rejected', N'Rejected IT Applicant', N'applicant.rejected.it@lifelink.test', @pwd, N'Active', @now, @now);

DECLARE @adminId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'admin.seed@lifelink.test');
DECLARE @itBloodId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'it.blood@lifelink.test');
DECLARE @itGeneralId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'it.general@lifelink.test');
DECLARE @doctorRahimId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'doctor.rahim@lifelink.test');
DECLARE @doctorSaraId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'doctor.sara@lifelink.test');
DECLARE @nurseBloodId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'nurse.blood@lifelink.test');
DECLARE @nurseWardId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'nurse.ward@lifelink.test');
DECLARE @patientAnikId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'patient.anik@lifelink.test');
DECLARE @patientMinaId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'patient.mina@lifelink.test');
DECLARE @patientRafiId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'patient.rafi@lifelink.test');
DECLARE @donorArifId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'donor.arif@lifelink.test');
DECLARE @donorNilaId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'donor.nila@lifelink.test');
DECLARE @donorKamalId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'donor.kamal@lifelink.test');
DECLARE @pendingDoctorApplicantId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'applicant.pending.doctor@lifelink.test');
DECLARE @pendingNurseApplicantId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'applicant.pending.nurse@lifelink.test');
DECLARE @rejectedItApplicantId BIGINT = (SELECT TOP 1 id FROM dbo.users WHERE email = N'applicant.rejected.it@lifelink.test');

IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @adminId AND role_id = @roleAdmin) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@adminId, @roleAdmin, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @itBloodId AND role_id = @roleIT) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@itBloodId, @roleIT, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @itGeneralId AND role_id = @roleIT) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@itGeneralId, @roleIT, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @doctorRahimId AND role_id = @roleDoctor) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@doctorRahimId, @roleDoctor, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @doctorSaraId AND role_id = @roleDoctor) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@doctorSaraId, @roleDoctor, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @nurseBloodId AND role_id = @roleNurse) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@nurseBloodId, @roleNurse, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @nurseWardId AND role_id = @roleNurse) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@nurseWardId, @roleNurse, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @patientAnikId AND role_id = @rolePatient) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@patientAnikId, @rolePatient, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @patientMinaId AND role_id = @rolePatient) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@patientMinaId, @rolePatient, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @patientRafiId AND role_id = @rolePatient) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@patientRafiId, @rolePatient, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @donorArifId AND role_id = @roleDonor) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@donorArifId, @roleDonor, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @donorNilaId AND role_id = @roleDonor) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@donorNilaId, @roleDonor, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @donorKamalId AND role_id = @roleDonor) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@donorKamalId, @roleDonor, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @pendingDoctorApplicantId AND role_id = @roleApplicant) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@pendingDoctorApplicantId, @roleApplicant, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @pendingNurseApplicantId AND role_id = @roleApplicant) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@pendingNurseApplicantId, @roleApplicant, @now, @adminId);
IF NOT EXISTS (SELECT 1 FROM dbo.user_roles WHERE user_id = @rejectedItApplicantId AND role_id = @roleApplicant) INSERT INTO dbo.user_roles (user_id, role_id, assigned_at, assigned_by_user_id) VALUES (@rejectedItApplicantId, @roleApplicant, @now, @adminId);

IF NOT EXISTS (SELECT 1 FROM dbo.permissions WHERE permission_code = N'admin.applications.review') INSERT INTO dbo.permissions (permission_code, description, created_at, updated_at) VALUES (N'admin.applications.review', N'Review applications', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.permissions WHERE permission_code = N'admin.staff.setup') INSERT INTO dbo.permissions (permission_code, description, created_at, updated_at) VALUES (N'admin.staff.setup', N'Staff setup', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.permissions WHERE permission_code = N'it.blood.operations') INSERT INTO dbo.permissions (permission_code, description, created_at, updated_at) VALUES (N'it.blood.operations', N'Blood bank operations', @now, @now);
DECLARE @permReview BIGINT = (SELECT TOP 1 id FROM dbo.permissions WHERE permission_code = N'admin.applications.review');
DECLARE @permSetup BIGINT = (SELECT TOP 1 id FROM dbo.permissions WHERE permission_code = N'admin.staff.setup');
DECLARE @permItBlood BIGINT = (SELECT TOP 1 id FROM dbo.permissions WHERE permission_code = N'it.blood.operations');
IF NOT EXISTS (SELECT 1 FROM dbo.role_permissions WHERE role_id = @roleAdmin AND permission_id = @permReview) INSERT INTO dbo.role_permissions (role_id, permission_id, granted_at) VALUES (@roleAdmin, @permReview, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.role_permissions WHERE role_id = @roleAdmin AND permission_id = @permSetup) INSERT INTO dbo.role_permissions (role_id, permission_id, granted_at) VALUES (@roleAdmin, @permSetup, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.role_permissions WHERE role_id = @roleIT AND permission_id = @permItBlood) INSERT INTO dbo.role_permissions (role_id, permission_id, granted_at) VALUES (@roleIT, @permItBlood, @now);

IF NOT EXISTS (SELECT 1 FROM dbo.doctors WHERE doctor_id = @doctorRahimId) INSERT INTO dbo.doctors (doctor_id, department_id, specialization, license_number, is_active, created_at, updated_at) VALUES (@doctorRahimId, @deptCardio, N'Cardiology', N'DOC-CARD-1001', 1, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.doctors WHERE doctor_id = @doctorSaraId) INSERT INTO dbo.doctors (doctor_id, department_id, specialization, license_number, is_active, created_at, updated_at) VALUES (@doctorSaraId, @deptNeuro, N'Neurology', N'DOC-NEURO-1002', 1, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.nurses WHERE nurse_id = @nurseBloodId) INSERT INTO dbo.nurses (nurse_id, department_id, ward_assignment_note, is_active, created_at, updated_at) VALUES (@nurseBloodId, @deptBlood, N'Blood bank donor screening desk', 1, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.nurses WHERE nurse_id = @nurseWardId) INSERT INTO dbo.nurses (nurse_id, department_id, ward_assignment_note, is_active, created_at, updated_at) VALUES (@nurseWardId, @deptGeneral, N'General ward day shift', 1, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.patients WHERE patient_id = @patientAnikId) INSERT INTO dbo.patients (patient_id, blood_group, emergency_contact_name, emergency_contact_phone, is_active, created_at, updated_at) VALUES (@patientAnikId, N'A+', N'Rima Hasan', N'01710000001', 1, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.patients WHERE patient_id = @patientMinaId) INSERT INTO dbo.patients (patient_id, blood_group, emergency_contact_name, emergency_contact_phone, is_active, created_at, updated_at) VALUES (@patientMinaId, N'O-', N'Karim Uddin', N'01710000002', 1, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.patients WHERE patient_id = @patientRafiId) INSERT INTO dbo.patients (patient_id, blood_group, emergency_contact_name, emergency_contact_phone, is_active, created_at, updated_at) VALUES (@patientRafiId, N'B+', N'Salma Chowdhury', N'01710000003', 1, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.department_admins WHERE user_id = @itBloodId AND department_id = @deptBlood) INSERT INTO dbo.department_admins (user_id, department_id, assigned_at) VALUES (@itBloodId, @deptBlood, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.department_admins WHERE user_id = @itGeneralId AND department_id = @deptGeneral) INSERT INTO dbo.department_admins (user_id, department_id, assigned_at) VALUES (@itGeneralId, @deptGeneral, @now);

IF NOT EXISTS (SELECT 1 FROM dbo.care_units WHERE department_id = @deptCardio AND unit_name = N'Cardio ICU') INSERT INTO dbo.care_units (department_id, unit_type, unit_name, floor, is_active, created_at, updated_at) VALUES (@deptCardio, N'ICU', N'Cardio ICU', 5, 1, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.care_units WHERE department_id = @deptGeneral AND unit_name = N'General Ward A') INSERT INTO dbo.care_units (department_id, unit_type, unit_name, floor, is_active, created_at, updated_at) VALUES (@deptGeneral, N'Ward', N'General Ward A', 3, 1, @now, @now);
DECLARE @careCardio BIGINT = (SELECT TOP 1 id FROM dbo.care_units WHERE department_id = @deptCardio AND unit_name = N'Cardio ICU');
DECLARE @careGeneral BIGINT = (SELECT TOP 1 id FROM dbo.care_units WHERE department_id = @deptGeneral AND unit_name = N'General Ward A');
IF NOT EXISTS (SELECT 1 FROM dbo.beds WHERE care_unit_id = @careCardio AND bed_code = N'CICU-01') INSERT INTO dbo.beds (care_unit_id, bed_code, status, is_active, created_at, updated_at) VALUES (@careCardio, N'CICU-01', N'Available', 1, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.beds WHERE care_unit_id = @careCardio AND bed_code = N'CICU-02') INSERT INTO dbo.beds (care_unit_id, bed_code, status, is_active, created_at, updated_at) VALUES (@careCardio, N'CICU-02', N'Occupied', 1, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.beds WHERE care_unit_id = @careGeneral AND bed_code = N'GW-A-01') INSERT INTO dbo.beds (care_unit_id, bed_code, status, is_active, created_at, updated_at) VALUES (@careGeneral, N'GW-A-01', N'Occupied', 1, @now, @now);

IF NOT EXISTS (SELECT 1 FROM dbo.job_applications WHERE user_id = @pendingDoctorApplicantId AND applied_role_id = @roleDoctor AND status = N'Pending') INSERT INTO dbo.job_applications (user_id, applied_role_id, applied_department_id, status, applied_at, created_at, updated_at) VALUES (@pendingDoctorApplicantId, @roleDoctor, @deptCardio, N'Pending', DATEADD(DAY, -2, @now), DATEADD(DAY, -2, @now), DATEADD(DAY, -2, @now));
IF NOT EXISTS (SELECT 1 FROM dbo.job_applications WHERE user_id = @pendingNurseApplicantId AND applied_role_id = @roleNurse AND status = N'Pending') INSERT INTO dbo.job_applications (user_id, applied_role_id, applied_department_id, status, applied_at, created_at, updated_at) VALUES (@pendingNurseApplicantId, @roleNurse, NULL, N'Pending', DATEADD(DAY, -1, @now), DATEADD(DAY, -1, @now), DATEADD(DAY, -1, @now));
IF NOT EXISTS (SELECT 1 FROM dbo.job_applications WHERE user_id = @rejectedItApplicantId AND applied_role_id = @roleIT AND status = N'Rejected') INSERT INTO dbo.job_applications (user_id, applied_role_id, applied_department_id, status, applied_at, reviewed_by_user_id, reviewed_at, review_notes, created_at, updated_at) VALUES (@rejectedItApplicantId, @roleIT, @deptGeneral, N'Rejected', DATEADD(DAY, -4, @now), @adminId, DATEADD(DAY, -3, @now), N'Rejected for current cycle.', DATEADD(DAY, -4, @now), DATEADD(DAY, -3, @now));

IF NOT EXISTS (SELECT 1 FROM dbo.admissions WHERE patient_user_id = @patientAnikId AND diagnosis = N'Acute chest pain observation') INSERT INTO dbo.admissions (patient_user_id, department_id, admitted_by_doctor_id, diagnosis, care_level_requested, care_level_assigned, status, admit_date, notes, created_at, updated_at) VALUES (@patientAnikId, @deptCardio, @doctorRahimId, N'Acute chest pain observation', N'ICU', N'ICU', N'Admitted', DATEADD(DAY, -1, @now), N'Continuous monitoring required.', DATEADD(DAY, -1, @now), DATEADD(DAY, -1, @now));
IF NOT EXISTS (SELECT 1 FROM dbo.admissions WHERE patient_user_id = @patientMinaId AND diagnosis = N'Severe anemia with dizziness') INSERT INTO dbo.admissions (patient_user_id, department_id, admitted_by_doctor_id, diagnosis, care_level_requested, care_level_assigned, status, admit_date, notes, created_at, updated_at) VALUES (@patientMinaId, @deptGeneral, @doctorSaraId, N'Severe anemia with dizziness', N'Ward', N'Ward', N'Admitted', DATEADD(HOUR, -18, @now), N'Blood support likely needed.', DATEADD(HOUR, -18, @now), DATEADD(HOUR, -18, @now));
DECLARE @admissionAnik BIGINT = (SELECT TOP 1 id FROM dbo.admissions WHERE patient_user_id = @patientAnikId ORDER BY id DESC);
DECLARE @admissionMina BIGINT = (SELECT TOP 1 id FROM dbo.admissions WHERE patient_user_id = @patientMinaId ORDER BY id DESC);
DECLARE @bedCardio2 BIGINT = (SELECT TOP 1 id FROM dbo.beds WHERE bed_code = N'CICU-02');
DECLARE @bedGeneral1 BIGINT = (SELECT TOP 1 id FROM dbo.beds WHERE bed_code = N'GW-A-01');
IF NOT EXISTS (SELECT 1 FROM dbo.bed_assignments WHERE admission_id = @admissionAnik AND released_at IS NULL) INSERT INTO dbo.bed_assignments (admission_id, bed_id, assigned_by_user_id, assigned_at, created_at, updated_at) VALUES (@admissionAnik, @bedCardio2, @itGeneralId, DATEADD(HOUR, -20, @now), DATEADD(HOUR, -20, @now), DATEADD(HOUR, -20, @now));
IF NOT EXISTS (SELECT 1 FROM dbo.bed_assignments WHERE admission_id = @admissionMina AND released_at IS NULL) INSERT INTO dbo.bed_assignments (admission_id, bed_id, assigned_by_user_id, assigned_at, created_at, updated_at) VALUES (@admissionMina, @bedGeneral1, @itGeneralId, DATEADD(HOUR, -16, @now), DATEADD(HOUR, -16, @now), DATEADD(HOUR, -16, @now));

IF NOT EXISTS (SELECT 1 FROM dbo.doctor_appointment_rules WHERE doctor_user_id = @doctorRahimId AND department_id = @deptCardio AND day_of_week = 1) INSERT INTO dbo.doctor_appointment_rules (doctor_user_id, department_id, day_of_week, start_time, end_time, daily_capacity, is_active, created_at, updated_at) VALUES (@doctorRahimId, @deptCardio, 1, '09:00:00', '12:30:00', 18, 1, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.doctor_appointment_rules WHERE doctor_user_id = @doctorSaraId AND department_id = @deptNeuro AND day_of_week = 3) INSERT INTO dbo.doctor_appointment_rules (doctor_user_id, department_id, day_of_week, start_time, end_time, daily_capacity, is_active, created_at, updated_at) VALUES (@doctorSaraId, @deptNeuro, 3, '10:00:00', '14:00:00', 14, 1, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.appointments WHERE patient_id = @patientAnikId AND status = N'Pending') INSERT INTO dbo.appointments (patient_id, department_id, doctor_user_id, appointment_datetime, status, created_at, updated_at) VALUES (@patientAnikId, @deptCardio, @doctorRahimId, DATEADD(HOUR, 9, DATEADD(DAY, 1, CAST(@now AS DATE))), N'Pending', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.appointments WHERE patient_id = @patientMinaId AND status = N'Approved') INSERT INTO dbo.appointments (patient_id, department_id, doctor_user_id, appointment_datetime, status, created_at, updated_at) VALUES (@patientMinaId, @deptGeneral, @doctorSaraId, DATEADD(HOUR, 11, DATEADD(DAY, 2, CAST(@now AS DATE))), N'Approved', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.appointments WHERE patient_id = @patientRafiId AND status = N'Rejected') INSERT INTO dbo.appointments (patient_id, department_id, doctor_user_id, appointment_datetime, status, cancel_reason, created_at, updated_at) VALUES (@patientRafiId, @deptGeneral, NULL, DATEADD(HOUR, 15, DATEADD(DAY, 3, CAST(@now AS DATE))), N'Rejected', N'No active rule for selected date.', @now, @now);
IF COL_LENGTH('dbo.appointments', 'appointment_date') IS NOT NULL UPDATE dbo.appointments SET appointment_date = CONVERT(date, appointment_datetime) WHERE appointment_date IS NULL;

IF NOT EXISTS (SELECT 1 FROM dbo.medical_records WHERE patient_id = @patientAnikId AND diagnosis = N'Unstable angina follow-up') INSERT INTO dbo.medical_records (patient_id, admission_id, created_by_user_id, record_datetime, diagnosis, treatment_plan, notes, created_at, updated_at) VALUES (@patientAnikId, @admissionAnik, @doctorRahimId, DATEADD(HOUR, -10, @now), N'Unstable angina follow-up', N'ECG monitoring and medication adjustment.', N'Responding to treatment.', DATEADD(HOUR, -10, @now), DATEADD(HOUR, -10, @now));
IF NOT EXISTS (SELECT 1 FROM dbo.nurse_vital_sign_logs WHERE admission_id = @admissionMina AND nurse_id = @nurseWardId) INSERT INTO dbo.nurse_vital_sign_logs (admission_id, patient_id, nurse_id, measured_at, temperature_c, pulse_bpm, systolic_bp, diastolic_bp, respiration_rate, spo2_percent, note, created_at, updated_at) VALUES (@admissionMina, @patientMinaId, @nurseWardId, DATEADD(HOUR, -6, @now), 37.1, 92, 100, 65, 20, 97, N'Patient stable but weak.', DATEADD(HOUR, -6, @now), DATEADD(HOUR, -6, @now));

IF NOT EXISTS (SELECT 1 FROM dbo.blood_banks WHERE bank_name = N'LifeLink North Blood Bank') INSERT INTO dbo.blood_banks (bank_name, location, is_active, created_at, updated_at) VALUES (N'LifeLink North Blood Bank', N'Uttara', 1, @now, @now);
DECLARE @bankCentralId BIGINT = (SELECT TOP 1 id FROM dbo.blood_banks WHERE bank_name = N'LifeLink Central Blood Bank');
DECLARE @bankNorthId BIGINT = (SELECT TOP 1 id FROM dbo.blood_banks WHERE bank_name = N'LifeLink North Blood Bank');
IF NOT EXISTS (SELECT 1 FROM dbo.donor_profiles WHERE donor_id = @donorArifId) INSERT INTO dbo.donor_profiles (donor_id, blood_group, last_donation_date, is_eligible, notes, created_at, updated_at) VALUES (@donorArifId, N'A+', DATEADD(DAY, -120, @now), 1, N'Regular volunteer donor.', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.donor_profiles WHERE donor_id = @donorNilaId) INSERT INTO dbo.donor_profiles (donor_id, blood_group, last_donation_date, is_eligible, notes, created_at, updated_at) VALUES (@donorNilaId, N'O-', DATEADD(DAY, -200, @now), 1, N'O negative emergency donor.', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.donor_profiles WHERE donor_id = @donorKamalId) INSERT INTO dbo.donor_profiles (donor_id, blood_group, last_donation_date, is_eligible, notes, created_at, updated_at) VALUES (@donorKamalId, N'B+', DATEADD(DAY, -20, @now), 0, N'Temporarily ineligible due to low hemoglobin.', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.blood_inventory WHERE blood_bank_id = @bankCentralId AND blood_group = N'A+' AND component_type = N'WholeBlood') INSERT INTO dbo.blood_inventory (blood_bank_id, blood_group, component_type, units_available, last_updated_at, created_at, updated_at) VALUES (@bankCentralId, N'A+', N'WholeBlood', 14, @now, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.blood_inventory WHERE blood_bank_id = @bankCentralId AND blood_group = N'O-' AND component_type = N'RBC') INSERT INTO dbo.blood_inventory (blood_bank_id, blood_group, component_type, units_available, last_updated_at, created_at, updated_at) VALUES (@bankCentralId, N'O-', N'RBC', 9, @now, @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.blood_inventory WHERE blood_bank_id = @bankNorthId AND blood_group = N'B+' AND component_type = N'Plasma') INSERT INTO dbo.blood_inventory (blood_bank_id, blood_group, component_type, units_available, last_updated_at, created_at, updated_at) VALUES (@bankNorthId, N'B+', N'Plasma', 7, @now, @now, @now);

IF NOT EXISTS (SELECT 1 FROM dbo.blood_requests WHERE patient_id = @patientMinaId AND notes = N'Urgent transfusion candidate from general ward.') INSERT INTO dbo.blood_requests (patient_id, admission_id, department_id, requested_by_user_id, blood_group_needed, component_type, units_required, urgency, status, request_date, notes, blood_bank_id, created_at, updated_at) VALUES (@patientMinaId, @admissionMina, @deptGeneral, @patientMinaId, N'O-', N'RBC', 2, N'Urgent', N'Pending', DATEADD(HOUR, -5, @now), N'Urgent transfusion candidate from general ward.', @bankCentralId, DATEADD(HOUR, -5, @now), DATEADD(HOUR, -5, @now));
IF NOT EXISTS (SELECT 1 FROM dbo.blood_requests WHERE patient_id = @patientAnikId AND notes = N'Cardio request approved and awaiting unit issue.') INSERT INTO dbo.blood_requests (patient_id, admission_id, department_id, requested_by_user_id, blood_group_needed, component_type, units_required, urgency, status, request_date, notes, blood_bank_id, created_at, updated_at) VALUES (@patientAnikId, @admissionAnik, @deptCardio, @patientAnikId, N'A+', N'WholeBlood', 1, N'Normal', N'Approved', DATEADD(HOUR, -16, @now), N'Cardio request approved and awaiting unit issue.', @bankCentralId, DATEADD(HOUR, -16, @now), DATEADD(HOUR, -16, @now));
IF NOT EXISTS (SELECT 1 FROM dbo.blood_requests WHERE patient_id = @patientRafiId AND notes = N'Request rejected because donor screening failed.') INSERT INTO dbo.blood_requests (patient_id, admission_id, department_id, requested_by_user_id, blood_group_needed, component_type, units_required, urgency, status, request_date, notes, blood_bank_id, created_at, updated_at) VALUES (@patientRafiId, NULL, @deptGeneral, @patientRafiId, N'AB+', N'Platelets', 2, N'Normal', N'Rejected', DATEADD(DAY, -3, @now), N'Request rejected because donor screening failed.', @bankNorthId, DATEADD(DAY, -3, @now), DATEADD(DAY, -3, @now));
DECLARE @requestPending BIGINT = (SELECT TOP 1 id FROM dbo.blood_requests WHERE notes = N'Urgent transfusion candidate from general ward.');
DECLARE @requestApproved BIGINT = (SELECT TOP 1 id FROM dbo.blood_requests WHERE notes = N'Cardio request approved and awaiting unit issue.');

IF NOT EXISTS (SELECT 1 FROM dbo.donor_availabilities WHERE donor_id = @donorArifId AND week_start_date = CAST(@now AS DATE)) INSERT INTO dbo.donor_availabilities (donor_id, week_start_date, is_available, max_bags_possible, notes, created_at, updated_at) VALUES (@donorArifId, CAST(@now AS DATE), 1, 1, N'Available this week.', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.donor_availabilities WHERE donor_id = @donorKamalId AND week_start_date = CAST(@now AS DATE)) INSERT INTO dbo.donor_availabilities (donor_id, week_start_date, is_available, max_bags_possible, notes, created_at, updated_at) VALUES (@donorKamalId, CAST(@now AS DATE), 0, 0, N'Unavailable until follow-up.', @now, @now);
IF NOT EXISTS (SELECT 1 FROM dbo.donor_health_checks WHERE donor_id = @donorArifId AND notes = N'Fit to donate.') INSERT INTO dbo.donor_health_checks (donor_id, check_datetime, weight_kg, temperature_c, hemoglobin, notes, checked_by_user_id, created_at, updated_at) VALUES (@donorArifId, DATEADD(HOUR, -4, @now), 72.50, 36.60, 14.10, N'Fit to donate.', @nurseBloodId, DATEADD(HOUR, -4, @now), DATEADD(HOUR, -4, @now));
IF NOT EXISTS (SELECT 1 FROM dbo.donor_health_checks WHERE donor_id = @donorKamalId AND notes = N'Not eligible today due to hemoglobin level.') INSERT INTO dbo.donor_health_checks (donor_id, check_datetime, weight_kg, temperature_c, hemoglobin, notes, checked_by_user_id, created_at, updated_at) VALUES (@donorKamalId, DATEADD(HOUR, -2, @now), 69.00, 36.80, 11.10, N'Not eligible today due to hemoglobin level.', @nurseBloodId, DATEADD(HOUR, -2, @now), DATEADD(HOUR, -2, @now));
IF NOT EXISTS (SELECT 1 FROM dbo.blood_request_matches WHERE request_id = @requestPending AND donor_id = @donorNilaId) INSERT INTO dbo.blood_request_matches (request_id, donor_id, match_score, compatibility_label, status, notified_at, selected_by_user_id, notes, created_at, updated_at) VALUES (@requestPending, @donorNilaId, 98.50, N'Exact', N'Notified', DATEADD(HOUR, -1, @now), @itBloodId, N'Priority O- donor notified.', DATEADD(HOUR, -1, @now), DATEADD(HOUR, -1, @now));
IF NOT EXISTS (SELECT 1 FROM dbo.blood_request_matches WHERE request_id = @requestApproved AND donor_id = @donorArifId) INSERT INTO dbo.blood_request_matches (request_id, donor_id, match_score, compatibility_label, status, notified_at, responded_at, selected_by_user_id, notes, created_at, updated_at) VALUES (@requestApproved, @donorArifId, 95.20, N'Exact', N'Accepted', DATEADD(HOUR, -14, @now), DATEADD(HOUR, -13, @now), @itBloodId, N'Donor accepted and waiting fulfillment.', DATEADD(HOUR, -14, @now), DATEADD(HOUR, -13, @now));
DECLARE @matchPending BIGINT = (SELECT TOP 1 id FROM dbo.blood_request_matches WHERE request_id = @requestPending AND donor_id = @donorNilaId);
IF NOT EXISTS (SELECT 1 FROM dbo.donor_notifications WHERE donor_id = @donorNilaId AND request_id = @requestPending) INSERT INTO dbo.donor_notifications (donor_id, request_id, match_id, notification_title, notification_message, status, sent_at, created_by_user_id, created_at, updated_at) VALUES (@donorNilaId, @requestPending, @matchPending, N'Urgent blood request', N'You are matched for an urgent request.', N'Sent', DATEADD(HOUR, -1, @now), @itBloodId, DATEADD(HOUR, -1, @now), DATEADD(HOUR, -1, @now));
DECLARE @hcArif BIGINT = (SELECT TOP 1 id FROM dbo.donor_health_checks WHERE donor_id = @donorArifId ORDER BY id DESC);
IF NOT EXISTS (SELECT 1 FROM dbo.blood_donations WHERE donor_id = @donorArifId AND linked_request_id = @requestApproved) INSERT INTO dbo.blood_donations (donor_id, blood_bank_id, donation_datetime, blood_group, component_type, units_donated, recorded_by_user_id, linked_request_id, donor_health_check_id, notes, created_at, updated_at) VALUES (@donorArifId, @bankCentralId, DATEADD(HOUR, -2, @now), N'A+', N'WholeBlood', 1, @itBloodId, @requestApproved, @hcArif, N'Donation logged for approved request.', DATEADD(HOUR, -2, @now), DATEADD(HOUR, -2, @now));

IF NOT EXISTS (SELECT 1 FROM dbo.doctor_reviews WHERE doctor_user_id = @doctorRahimId AND patient_id = @patientAnikId)
    INSERT INTO dbo.doctor_reviews (doctor_user_id, patient_id, department_id, appointment_id, rating, review_text, is_visible, created_at, updated_at)
    VALUES (@doctorRahimId, @patientAnikId, @deptCardio, NULL, 5, N'Excellent communication and quick diagnosis.', 1, @now, @now);
GO

